version: '3'

services:
    app:
        build: .
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment: 
            - DB_HOST=db
            - DB_DATABASE=myapp
            - DB_USERNAME=root
            - DB_PASSWORD=123456
        volumes: 
            - .:/app/
        networks:
            - app-network
        depends_on:
            - db
    
    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        networks:
            - app-network
            
    db:
        image: mysql:8
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app-network
    
    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network    

networks:
    app-network:
        driver: bridge